[package]
name = "nanohat_shizuku"
version = "0.1.0"
edition = "2021"

[dependencies]
gpio = "0.4.1"
local-ip-address = "0.6.3"
nanohat-oled = "0.2.0"

[profile.release]
lto = "fat"
strip = "symbols"
codegen-units = 1